package app.shosetsu.android.extensionbuilder

/**
 * Generates a Shosetsu Lua scaffold targeting the runtime contract consumed by this app's
 * IExtension usage (metadata + `parseNovel`, `getPassage`, `listings`, and optional `search`).
 */
class ExtensionGenerator {

	fun generateLua(spec: ExtensionSpec): String {
		val normalizedBaseUrl = spec.baseUrl.trimEnd('/')
		val escapedName = escapeLua(spec.name)
		val escapedLang = escapeLua(spec.lang)
		val escapedBaseUrl = escapeLua(normalizedBaseUrl)
		val escapedVersion = escapeLua(spec.version)
		val escapedAuthor = escapeLua(spec.author.orEmpty())
		val escapedId = spec.runtimeId
		val metadataHeader = metadataHeader(spec)

		val headersTable = buildHeadersTable(spec)
		val userAgentLine = spec.userAgent?.takeIf { it.isNotBlank() }
			?.let { "\theaders[\"User-Agent\"] = \"${escapeLua(it)}\"" }
			?: "\t-- TODO: optionally override User-Agent here"

		val parsingFunctions = parsingFunctions(spec)
		val searchFunction = searchFunction(spec)
		val listings = listings(spec)
		val chapterType = if (spec.parsing.enabled && spec.parsing.mode == ParsingMode.BASIC && spec.parsing.basic.contentOutput == ContentOutput.TEXT) {
			"ChapterType.String"
		} else {
			"ChapterType.HTML"
		}

		val body = """
			-- Generated by Shosetsu Extension Builder
			-- Runtime target: Kotlin lib (IExtension / LuaExtension) used by this app build.
			
			local ID = $escapedId
			local NAME = ${quote(escapedName)}
			local VERSION = ${quote(escapedVersion)}
			local BASE_URL = ${quote(escapedBaseUrl)}
			local LANG = ${quote(escapedLang)}
			local AUTHOR = ${quote(escapedAuthor)}
			
			local baseURL = BASE_URL
			local headers = {
			$headersTable
			}
			$userAgentLine
			
			local headersConversionWarningShown = false
			local function resolveHeaders(rawHeaders)
				if rawHeaders == nil or next(rawHeaders) == nil then
					return nil
				end
				if type(rawHeaders) ~= "table" then
					return rawHeaders
				end
				if type(BuildHeaders) == "function" then
					return BuildHeaders(rawHeaders)
				end
				if type(toHeaders) == "function" then
					return toHeaders(rawHeaders)
				end
				if type(Headers) == "function" then
					local ok, converted = pcall(Headers, rawHeaders)
					if ok then
						return converted
					end
				end
				if not headersConversionWarningShown then
					print("Headers were specified but this runtime requires okhttp3.Headers; header conversion is not available.")
					headersConversionWarningShown = true
				end
				return nil
			end
			
			local function GETDocument(url, customHeaders)
				local h = resolveHeaders(customHeaders or headers)
				if h == nil then
					return Document(GET(url))
				end
				return Document(GET(url, h))
			end

			local function urlEncode(s)
				if EncodeUrl ~= nil then return EncodeUrl(s) end
				if EncodeURL ~= nil then return EncodeURL(s) end
				if URLEncode ~= nil then return URLEncode(s) end
				return tostring(s):gsub(" ", "%%20")
			end

			local function trySelect(root, selector)
				if root == nil then return nil end
				local ok, selected = pcall(function() return root:select(selector) end)
				if ok then return selected end
				return nil
			end

			local function firstElement(root, selector)
				local list = trySelect(root, selector)
				if list == nil then return nil end
				if list.first ~= nil then
					local ok, first = pcall(function() return list:first() end)
					if ok then return first end
				end
				local ok, first = pcall(function() return list:get(0) end)
				if ok then return first end
				return nil
			end

			local function safeAttr(node, attr)
				if node == nil then return "" end
				local ok, value = pcall(function() return node:attr(attr) end)
				if not ok or value == nil then return "" end
				return tostring(value)
			end

			local function safeText(node)
				if node == nil then return "" end
				local ok, value = pcall(function() return node:text() end)
				if not ok or value == nil then return "" end
				return tostring(value)
			end

			local function readValue(node, source, attr)
				if source == "ATTR" then return safeAttr(node, attr) end
				return safeText(node)
			end

			local function normalizeURL(rawURL)
				if rawURL == nil then return "" end
				local url = tostring(rawURL)
				if url == "" then return "" end
				if StartsWith(url, "http") then return url end
				if StartsWith(url, "//") then return "https:" .. url end
				if StartsWith(url, "/") then return baseURL .. url end
				return baseURL .. "/" .. url
			end

			$parsingFunctions
			
			$searchFunction
			
			return {
				id = ID,
				name = NAME,
				imageURL = "https://raw.githubusercontent.com/shosetsuorg/extensions/dev/icons/default.png",
				baseURL = baseURL,
				chapterType = $chapterType,
				lang = LANG,
				author = AUTHOR,
				version = VERSION,
				hasSearch = ${spec.capabilities.supportsSearch},
				startIndex = 1,
				listings = {
					$listings
				},
				parseNovel = parseNovel,
				getPassage = getPassage${if (spec.capabilities.supportsSearch) ",\n\t\t\t\tsearch = search" else ""},
				shrinkURL = function(url)
					return url:gsub(baseURL, "")
				end,
				expandURL = function(url)
					if StartsWith(url, "http") then return url end
					return baseURL .. url
				end${if (spec.capabilities.supportsFilters) ",\n\t\t\t\tsearchFilters = {\n\t\t\t\t\t-- TODO: insert search filter models supported by runtime\n\t\t\t\t}" else ""}${if (spec.capabilities.supportsGenres) ",\n\t\t\t\tgenres = {\n\t\t\t\t\t-- TODO: insert known genres/tags\n\t\t\t\t}" else ""}
			}
		""".trimIndent()

		return buildString {
			append(metadataHeader)
			append('\n')
			append(body)
		}
	}

	private fun parsingFunctions(spec: ExtensionSpec): String {
		if (!spec.parsing.enabled) return templateFunctions()
		if (spec.parsing.mode == ParsingMode.ADVANCED) {
			val snippet = if (containsUnsafeGlobalAssignment(spec.parsing.luaOverrideSnippet)) {
				"error(\"Global assignments are not allowed in Lua extensions; use local variables.\")"
			} else {
				spec.parsing.luaOverrideSnippet.trim()
			}
			return """
				local function parseListingDocument(document, requestURL, sourceLabel)
					local data = { document = document, url = requestURL, source = sourceLabel, baseURL = baseURL }
					$snippet
					return (data and data.listings) or {}
				end
				
				local function parseNovel(novelURL, loadChapters)
					local url = normalizeURL(novelURL)
					local document = GETDocument(url)
					local data = { document = document, url = url, baseURL = baseURL, loadChapters = loadChapters }
					$snippet
					if data and data.novel ~= nil then return data.novel end
					return NovelInfo({
						title = "",
						imageURL = "",
						description = "",
						genres = {},
						authors = {},
						artists = {},
						status = NovelStatus.UNKNOWN
					})
				end
				
				local function getPassage(chapterURL)
					local url = normalizeURL(chapterURL)
					local document = GETDocument(url)
					local data = { document = document, url = url, baseURL = baseURL }
					$snippet
					return (data and data.passage) or ""
				end
			""".trimIndent()
		}
		return basicFunctions(spec.parsing.basic)
	}

	private fun basicFunctions(basic: BasicParsingSpec): String {
		val titleAttr = escapeLua(basic.titleAttr ?: "")
		val novelTitleAttr = escapeLua(basic.novelTitleAttr ?: "")
		val chapterTitleAttr = escapeLua(basic.chapterTitleAttr ?: "")
		val removeSelector = escapeLua(basic.removeSelector.orEmpty())
		val contentRead = if (basic.contentOutput == ContentOutput.TEXT) "safeText(contentNode)" else "tostring(contentNode)"
		return """
			local function parseListingDocument(document, requestURL, sourceLabel)
				local cards = trySelect(document, ${quote(escapeLua(basic.itemSelector))})
				if cards == nil then return {} end
				local okSize, size = pcall(function() return cards:size() end)
				if not okSize or size == nil or size <= 0 then
					local html = tostring(document)
					if html ~= nil and #html > 0 then
						print("[ExtensionBuilder] " .. sourceLabel .. " returned 0 items for " .. tostring(requestURL) .. ". HTML preview: " .. html:sub(1, 500))
					end
					return {}
				end
				local results = {}
				for i = 0, size - 1 do
					local card = cards:get(i)
					local titleNode = firstElement(card, ${quote(escapeLua(basic.titleSelector))})
					local linkNode = firstElement(card, ${quote(escapeLua(basic.urlSelector))})
					local imageNode = firstElement(card, ${quote(escapeLua(basic.imageSelector))})
					local title = readValue(titleNode, ${quote(basic.titleFrom.name)}, ${quote(titleAttr)})
					local rawUrl = safeAttr(linkNode, ${quote(escapeLua(basic.urlAttr))})
					local imageURL = safeAttr(imageNode, ${quote(escapeLua(basic.imageAttr))})
					local url = normalizeURL(rawUrl)
					if url ~= "" and title ~= "" then
						table.insert(results, NovelListing(url, title, normalizeURL(imageURL)))
					end
				end
				return results
			end
			
			local function parseNovel(novelURL, loadChapters)
				local url = normalizeURL(novelURL)
				local document = GETDocument(url)
				local titleNode = firstElement(document, ${quote(escapeLua(basic.novelTitleSelector))})
				local coverNode = firstElement(document, ${quote(escapeLua(basic.coverSelector))})
				local descriptionNode = firstElement(document, ${quote(escapeLua(basic.descriptionSelector))})
				local novel = NovelInfo({
					title = readValue(titleNode, ${quote(basic.novelTitleFrom.name)}, ${quote(novelTitleAttr)}),
					imageURL = normalizeURL(safeAttr(coverNode, ${quote(escapeLua(basic.coverAttr))})),
					description = safeText(descriptionNode),
					genres = map(trySelect(document, ${quote(escapeLua(basic.genreSelector))}) or {}, safeText),
					authors = map(trySelect(document, ${quote(escapeLua(basic.authorSelector))}) or {}, safeText),
					artists = {},
					status = NovelStatus.UNKNOWN
				})
				local statusSelector = ${quote(escapeLua(basic.statusSelector))}
				if statusSelector ~= "" then
					local statusText = safeText(firstElement(document, statusSelector)):lower()
					if statusText:find("ongoing") ~= nil then novel.status = NovelStatus.PUBLISHING end
					if statusText:find("completed") ~= nil or statusText:find("complete") ~= nil then novel.status = NovelStatus.COMPLETED end
					if statusText:find("hiatus") ~= nil then novel.status = NovelStatus.PAUSED end
				end
				if loadChapters then
					novel.chapters = {}
					local chapterNodes = trySelect(document, ${quote(escapeLua(basic.chapterItemSelector))})
					if chapterNodes ~= nil then
						local okSize, chapterCount = pcall(function() return chapterNodes:size() end)
						if okSize and chapterCount ~= nil then
							for i = 0, chapterCount - 1 do
								local chapterNode = chapterNodes:get(i)
								local chapterTitleNode = firstElement(chapterNode, ${quote(escapeLua(basic.chapterTitleSelector))})
								local chapterUrlNode = firstElement(chapterNode, ${quote(escapeLua(basic.chapterUrlSelector))})
								local chapterTitle = readValue(chapterTitleNode, ${quote(basic.chapterTitleFrom.name)}, ${quote(chapterTitleAttr)})
								local chapterURL = normalizeURL(safeAttr(chapterUrlNode, ${quote(escapeLua(basic.chapterUrlAttr))}))
								if chapterURL ~= "" and chapterTitle ~= "" then
									table.insert(novel.chapters, Chapter(chapterURL, chapterTitle))
								end
							end
						end
					end
				end
				return novel
			end
			
			local function getPassage(chapterURL)
				local url = normalizeURL(chapterURL)
				local document = GETDocument(url)
				local contentNode = firstElement(document, ${quote(escapeLua(basic.contentSelector))})
				if contentNode == nil then return "" end
				local removeSelector = ${quote(removeSelector)}
				if removeSelector ~= "" then
					local removeNodes = trySelect(contentNode, removeSelector)
					if removeNodes ~= nil then
						local okSize, removeCount = pcall(function() return removeNodes:size() end)
						if okSize and removeCount ~= nil then
							for i = 0, removeCount - 1 do
								local removeNode = removeNodes:get(i)
								pcall(function() removeNode:remove() end)
							end
						end
					end
				end
				return $contentRead
			end
		""".trimIndent()
	}

	private fun templateFunctions(): String = """
		local function extractListingValues(card)
			local linkNode = firstElement(card, "a[href]")
			local titleNode = firstElement(card, "h3, h2, .title, .novel-title")
			local imageNode = firstElement(card, "img[src], img[data-src], img[data-lazy-src]")

			local url = safeAttr(linkNode, "href")
			local title = safeText(titleNode)
			if title == "" then title = safeAttr(linkNode, "title") end
			if title == "" then title = safeText(linkNode) end
			local imageURL = safeAttr(imageNode, "src")
			if imageURL == "" then imageURL = safeAttr(imageNode, "data-src") end
			if imageURL == "" then imageURL = safeAttr(imageNode, "data-lazy-src") end

			return normalizeURL(url), title, normalizeURL(imageURL)
		end

		local function parseListingDocument(document, requestURL, sourceLabel)
			local selectors = { ".novel-item", ".novel-card", ".book-item", ".post", ".entry", "article", ".item", "li" }
			for _, selector in ipairs(selectors) do
				local nodes = trySelect(document, selector)
				if nodes ~= nil then
					local okSize, size = pcall(function() return nodes:size() end)
					if okSize and size ~= nil and size > 0 then
						local results = {}
						for i = 0, size - 1 do
							local node = nodes:get(i)
							local url, title, imageURL = extractListingValues(node)
							if url ~= "" and title ~= "" then
								table.insert(results, NovelListing(url, title, imageURL))
							end
						end
						if #results > 0 then return results end
					end
				end
			end
			local html = tostring(document)
			if html ~= nil and #html > 0 then
				print("[ExtensionBuilder] " .. sourceLabel .. " returned 0 items for " .. tostring(requestURL) .. ". HTML preview: " .. html:sub(1, 500))
			end
			return {}
		end

		local function parseNovel(novelURL, loadChapters)
			local url = normalizeURL(novelURL)
			local document = GETDocument(url)
			local novel = NovelInfo({
				title = "",
				imageURL = "",
				description = "",
				genres = {},
				authors = {},
				artists = {},
				status = NovelStatus.UNKNOWN
			})
			if loadChapters then novel.chapters = {} end
			return novel
		end

		local function getPassage(chapterURL)
			local url = normalizeURL(chapterURL)
			local document = GETDocument(url)
			return ""
		end
	""".trimIndent()

	private fun searchFunction(spec: ExtensionSpec): String {
		if (!spec.capabilities.supportsSearch) return ""
		return """
			local function search(data)
				local query = (data and data[QUERY]) or ""
				local page = (data and data[PAGE_INDEX]) or 1
				local url = baseURL .. "/search?q=" .. urlEncode(query) .. "&page=" .. tostring(page)
				local document = GETDocument(url)
				return parseListingDocument(document, url, "search")
			end
		""".trimIndent()
	}

	private fun listings(spec: ExtensionSpec): String = buildList {
		add(listingSnippet(name = "Popular", path = "/popular"))
		if (spec.capabilities.supportsLatest) add(listingSnippet(name = "Latest", path = "/latest"))
	}.joinToString(separator = ",\n")

	private fun containsUnsafeGlobalAssignment(snippet: String): Boolean =
		snippet.lineSequence().any { Regex("^\\s*[A-Za-z_][A-Za-z0-9_]*\\s*=").containsMatchIn(it) }

	private fun buildHeadersTable(spec: ExtensionSpec): String =
		spec.headers.joinToString(separator = ",\n") {
			"\t[${quote(escapeLua(it.key.trim()))}] = ${quote(escapeLua(it.value.trim()))}"
		}

	private fun escapeLua(value: String): String = value
		.replace("\\", "\\\\")
		.replace("\"", "\\\"")

	private fun quote(value: String): String = "\"$value\""

	private fun listingSnippet(name: String, path: String): String =
		"""
					Listing("$name", true, function(data)
						local page = (data and data[PAGE_INDEX]) or 1
						local url = baseURL .. "$path?page=" .. tostring(page)
						local document = GETDocument(url)
						return parseListingDocument(document, url, "$name listing")
					end)
		""".trimIndent()

	private fun metadataHeader(spec: ExtensionSpec): String =
		"-- {\"id\":${spec.runtimeId},\"ver\":\"${escapeLua(spec.version)}\",\"libVer\":\"1.0.0\",\"author\":\"${escapeLua(spec.author.orEmpty())}\",\"repo\":\"\",\"dep\":[]}"
}
